In [1]:
import numpy as np
print(np.__version__)

2.5.0


In [8]:
marks = np.array([50, 60, 70 , 80 , 90])
print(marks);
print(marks.shape)

[50 60 70 80 90]
(5,)


In [16]:
marks_2d = np.array([
    [30,40,50,60],
    [75,85,95,55]
])

print(marks_2d)
print(marks_2d.shape)
print(marks_2d.ndim)
print(marks_2d.dtype)
print(marks_2d.size)

[[30 40 50 60]
 [75 85 95 55]]
(2, 4)
2
int64
8


In [11]:
marks_3d = np.array([
[
    [30,50,70],
    [85, 45, 55]
],
[
    [50, 70, 80],
    [22, 56, 88]
]
])
print(marks_3d)
print(marks_3d.shape)

[[[30 50 70]
  [85 45 55]]

 [[50 70 80]
  [22 56 88]]]
(2, 2, 3)


(5,)


In [17]:
zeros_array = np.zeros((3,4))
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [35]:
ones_array = np.ones((2,3))
print("\nOnes:")
print(ones_array)


Ones:
[[1. 1. 1.]
 [1. 1. 1.]]


In [34]:
five_array = np.full((3,3),5)
print("\nFilled with 5:")
print(five_array)


Filled with 5:
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [33]:
arr = np.arange(10,51,10)
print("Using arange:")
print(arr)

Using arange:
[10 20 30 40 50]


In [32]:
arr = np.linspace(0, 100, 5)
print("\nUsing linspace:")
print(arr)


Using linspace:
[  0.  25.  50.  75. 100.]


In [31]:
identity_matrix = np.eye(4)
print("Identity Matrix:")
print(identity_matrix)


Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
diagonal_matrix = np.diag([10, 20, 30, 40])
print("\nDiagonal Matrix:")
print(diagonal_matrix)


Diagonal Matrix:
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]
