In [2]:
import numpy as np

one_d_array = np.array([75, 82, 90, 68, 95])
print("One_d_array", one_d_array)

One_d_array [75 82 90 68 95]


In [12]:
two_d_array = np.array([
    [75, 80, 85],
    [90, 88, 95]
])
print("Two-d array : ")
print(two_d_array)

Two-d array : 
[[75 80 85]
 [90 88 95]]


In [10]:
three_d_array = np.array([
    [  [75, 88, 95],
       [65, 55, 45]
    ],

    [
        [99, 33, 78],
        [90, 85, 25]
    ]
])

print("\nThree-d array :")
print(three_d_array)


Three-d array :
[[[75 88 95]
  [65 55 45]]

 [[99 33 78]
  [90 85 25]]]


In [15]:
print("Shape :", two_d_array.shape)
print("Dimensions : ", two_d_array.ndim)
print("Datatype : ", two_d_array.dtype)
print("Size : ", two_d_array.size)

Shape : (2, 3)
Dimensions :  2
Datatype :  int64
Size :  6


In [17]:
zeros_array = np.zeros((3,5))
print(zeros_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
ones_array = np.ones((3,5))
print(ones_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
filled_seven = np.full((3,3),5)
print(filled_seven)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [26]:
arr = np.arange(5, 50, 10)
print("Using arange :")
print(arr)

Using arange :
[ 5 15 25 35 45]


In [27]:
arr = np.linspace(0, 100, 6)
print("Using linspace")
print(arr)

Using linspace
[  0.  20.  40.  60.  80. 100.]


In [29]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [30]:
diagonal_matrix_ = np.diag([5, 10, 15, 20])
print(diagonal_matrix_)

[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]
