In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4])

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
np_array = np.array([1, 2, 3])
print(np_array * 2) 

[2 4 6]


In [5]:
import numpy as np

arr1D = np.array([1, 2, 3])
arr2D = np.array([[1, 2], [3, 4]])
arr3D = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr1D)
print(arr2D)
print(arr3D)

[1 2 3]
[[1 2]
 [3 4]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [14]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)
print(arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
int64
9


In [16]:
import numpy as np

arr = np.zeros((2, 3))
print(arr)
print(arr.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [17]:
import numpy as np

arr = np.ones((3, 2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [18]:
import numpy as np

arr = np.full((2, 2), 7)
print(arr)


[[7 7]
 [7 7]]


In [19]:
import numpy as np

arr = np.arange(1, 10, 2)
print(arr)

[1 3 5 7 9]


In [24]:
import numpy as np

arr = np.linspace(0, 1, 7)
print(arr)

[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [25]:
import numpy as np

arr = np.diag([1, 2, 3])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
